-- PatternOS — Seed Nifty 50 Universe
-- yfinance uses NSE suffix: RELIANCE.NS etc.

INSERT INTO universe (symbol, exchange, asset_class, name) VALUES
('RELIANCE.NS',  'NSE', 'equity', 'Reliance Industries'),
('TCS.NS',       'NSE', 'equity', 'Tata Consultancy Services'),
('HDFCBANK.NS',  'NSE', 'equity', 'HDFC Bank'),
('BHARTIARTL.NS','NSE', 'equity', 'Bharti Airtel'),
('ICICIBANK.NS', 'NSE', 'equity', 'ICICI Bank'),
('INFOSYS.NS',   'NSE', 'equity', 'Infosys'),
('SBIN.NS',      'NSE', 'equity', 'State Bank of India'),
('HINDUNILVR.NS','NSE', 'equity', 'Hindustan Unilever'),
('ITC.NS',       'NSE', 'equity', 'ITC Limited'),
('LT.NS',        'NSE', 'equity', 'Larsen & Toubro'),
('KOTAKBANK.NS', 'NSE', 'equity', 'Kotak Mahindra Bank'),
('AXISBANK.NS',  'NSE', 'equity', 'Axis Bank'),
('BAJFINANCE.NS','NSE', 'equity', 'Bajaj Finance'),
('ASIANPAINT.NS','NSE', 'equity', 'Asian Paints'),
('MARUTI.NS',    'NSE', 'equity', 'Maruti Suzuki'),
('TITAN.NS',     'NSE', 'equity', 'Titan Company'),
('SUNPHARMA.NS', 'NSE', 'equity', 'Sun Pharmaceutical'),
('WIPRO.NS',     'NSE', 'equity', 'Wipro'),
('ULTRACEMCO.NS','NSE', 'equity', 'UltraTech Cement'),
('NESTLEIND.NS', 'NSE', 'equity', 'Nestle India'),
('POWERGRID.NS', 'NSE', 'equity', 'Power Grid Corp'),
('NTPC.NS',      'NSE', 'equity', 'NTPC'),
('ONGC.NS',      'NSE', 'equity', 'Oil & Natural Gas Corp'),
('M&M.NS',       'NSE', 'equity', 'Mahindra & Mahindra'),
('TATAMOTORS.NS','NSE', 'equity', 'Tata Motors'),
('TATASTEEL.NS', 'NSE', 'equity', 'Tata Steel'),
('HCLTECH.NS',   'NSE', 'equity', 'HCL Technologies'),
('ADANIENT.NS',  'NSE', 'equity', 'Adani Enterprises'),
('ADANIPORTS.NS','NSE', 'equity', 'Adani Ports'),
('COALINDIA.NS', 'NSE', 'equity', 'Coal India'),
('JSWSTEEL.NS',  'NSE', 'equity', 'JSW Steel'),
('BAJAJFINSV.NS','NSE', 'equity', 'Bajaj Finserv'),
('TECHM.NS',     'NSE', 'equity', 'Tech Mahindra'),
('HINDALCO.NS',  'NSE', 'equity', 'Hindalco Industries'),
('DIVISLAB.NS',  'NSE', 'equity', 'Divi''s Laboratories'),
('CIPLA.NS',     'NSE', 'equity', 'Cipla'),
('DRREDDY.NS',   'NSE', 'equity', 'Dr Reddy''s Laboratories'),
('APOLLOHOSP.NS','NSE', 'equity', 'Apollo Hospitals'),
('BAJAJ-AUTO.NS','NSE', 'equity', 'Bajaj Auto'),
('EICHERMOT.NS', 'NSE', 'equity', 'Eicher Motors'),
('HEROMOTOCO.NS','NSE', 'equity', 'Hero MotoCorp'),
('BRITANNIA.NS', 'NSE', 'equity', 'Britannia Industries'),
('GRASIM.NS',    'NSE', 'equity', 'Grasim Industries'),
('TATACONSUM.NS','NSE', 'equity', 'Tata Consumer Products'),
('SHRIRAMFIN.NS','NSE', 'equity', 'Shriram Finance'),
('BEL.NS',       'NSE', 'equity', 'Bharat Electronics'),
('INDUSINDBK.NS','NSE', 'equity', 'IndusInd Bank'),
('BPCL.NS',      'NSE', 'equity', 'Bharat Petroleum'),
('SBILIFE.NS',   'NSE', 'equity', 'SBI Life Insurance'),
('HDFCLIFE.NS',  'NSE', 'equity', 'HDFC Life Insurance')
ON CONFLICT (symbol, exchange) DO NOTHING;
