-- Nifty 500 comprehensive seed
-- Uses ON CONFLICT DO UPDATE so existing records get sector/index_name populated

INSERT INTO universe (id, symbol, exchange, asset_class, name, active, sector, index_name) VALUES
-- ─── Nifty 50 ────────────────────────────────────────────────────────────────
(gen_random_uuid(), 'RELIANCE.NS',   'NSE', 'equity', 'Reliance Industries',          true, 'Energy',        'Nifty 50'),
(gen_random_uuid(), 'TCS.NS',        'NSE', 'equity', 'Tata Consultancy Services',    true, 'IT',            'Nifty 50'),
(gen_random_uuid(), 'HDFCBANK.NS',   'NSE', 'equity', 'HDFC Bank',                    true, 'Banking',       'Nifty 50'),
(gen_random_uuid(), 'BHARTIARTL.NS', 'NSE', 'equity', 'Bharti Airtel',                true, 'Telecom',       'Nifty 50'),
(gen_random_uuid(), 'ICICIBANK.NS',  'NSE', 'equity', 'ICICI Bank',                   true, 'Banking',       'Nifty 50'),
(gen_random_uuid(), 'INFOSYS.NS',    'NSE', 'equity', 'Infosys',                      true, 'IT',            'Nifty 50'),
(gen_random_uuid(), 'SBIN.NS',       'NSE', 'equity', 'State Bank of India',          true, 'Banking',       'Nifty 50'),
(gen_random_uuid(), 'HINDUNILVR.NS', 'NSE', 'equity', 'Hindustan Unilever',           true, 'FMCG',          'Nifty 50'),
(gen_random_uuid(), 'ITC.NS',        'NSE', 'equity', 'ITC',                          true, 'FMCG',          'Nifty 50'),
(gen_random_uuid(), 'LT.NS',         'NSE', 'equity', 'Larsen & Toubro',              true, 'Infrastructure','Nifty 50'),
(gen_random_uuid(), 'KOTAKBANK.NS',  'NSE', 'equity', 'Kotak Mahindra Bank',          true, 'Banking',       'Nifty 50'),
(gen_random_uuid(), 'AXISBANK.NS',   'NSE', 'equity', 'Axis Bank',                    true, 'Banking',       'Nifty 50'),
(gen_random_uuid(), 'BAJFINANCE.NS', 'NSE', 'equity', 'Bajaj Finance',                true, 'NBFC',          'Nifty 50'),
(gen_random_uuid(), 'ASIANPAINT.NS', 'NSE', 'equity', 'Asian Paints',                 true, 'Paints',        'Nifty 50'),
(gen_random_uuid(), 'MARUTI.NS',     'NSE', 'equity', 'Maruti Suzuki',                true, 'Auto',          'Nifty 50'),
(gen_random_uuid(), 'TITAN.NS',      'NSE', 'equity', 'Titan Company',                true, 'Consumer',      'Nifty 50'),
(gen_random_uuid(), 'SUNPHARMA.NS',  'NSE', 'equity', 'Sun Pharmaceutical',           true, 'Pharma',        'Nifty 50'),
(gen_random_uuid(), 'WIPRO.NS',      'NSE', 'equity', 'Wipro',                        true, 'IT',            'Nifty 50'),
(gen_random_uuid(), 'ULTRACEMCO.NS', 'NSE', 'equity', 'UltraTech Cement',             true, 'Cement',        'Nifty 50'),
(gen_random_uuid(), 'NESTLEIND.NS',  'NSE', 'equity', 'Nestle India',                 true, 'FMCG',          'Nifty 50'),
(gen_random_uuid(), 'POWERGRID.NS',  'NSE', 'equity', 'Power Grid Corporation',       true, 'Power',         'Nifty 50'),
(gen_random_uuid(), 'NTPC.NS',       'NSE', 'equity', 'NTPC',                         true, 'Power',         'Nifty 50'),
(gen_random_uuid(), 'ONGC.NS',       'NSE', 'equity', 'ONGC',                         true, 'Energy',        'Nifty 50'),
(gen_random_uuid(), 'M&M.NS',        'NSE', 'equity', 'Mahindra & Mahindra',          true, 'Auto',          'Nifty 50'),
(gen_random_uuid(), 'TATAMOTORS.NS', 'NSE', 'equity', 'Tata Motors',                  true, 'Auto',          'Nifty 50'),
(gen_random_uuid(), 'TATASTEEL.NS',  'NSE', 'equity', 'Tata Steel',                   true, 'Metals',        'Nifty 50'),
(gen_random_uuid(), 'HCLTECH.NS',    'NSE', 'equity', 'HCL Technologies',             true, 'IT',            'Nifty 50'),
(gen_random_uuid(), 'ADANIENT.NS',   'NSE', 'equity', 'Adani Enterprises',            true, 'Conglomerate',  'Nifty 50'),
(gen_random_uuid(), 'ADANIPORTS.NS', 'NSE', 'equity', 'Adani Ports',                  true, 'Infrastructure','Nifty 50'),
(gen_random_uuid(), 'COALINDIA.NS',  'NSE', 'equity', 'Coal India',                   true, 'Mining',        'Nifty 50'),
(gen_random_uuid(), 'JSWSTEEL.NS',   'NSE', 'equity', 'JSW Steel',                    true, 'Metals',        'Nifty 50'),
(gen_random_uuid(), 'BAJAJFINSV.NS', 'NSE', 'equity', 'Bajaj Finserv',                true, 'NBFC',          'Nifty 50'),
(gen_random_uuid(), 'TECHM.NS',      'NSE', 'equity', 'Tech Mahindra',                true, 'IT',            'Nifty 50'),
(gen_random_uuid(), 'HINDALCO.NS',   'NSE', 'equity', 'Hindalco Industries',          true, 'Metals',        'Nifty 50'),
(gen_random_uuid(), 'DIVISLAB.NS',   'NSE', 'equity', 'Divi''s Laboratories',         true, 'Pharma',        'Nifty 50'),
(gen_random_uuid(), 'CIPLA.NS',      'NSE', 'equity', 'Cipla',                        true, 'Pharma',        'Nifty 50'),
(gen_random_uuid(), 'DRREDDY.NS',    'NSE', 'equity', 'Dr Reddy''s Laboratories',     true, 'Pharma',        'Nifty 50'),
(gen_random_uuid(), 'APOLLOHOSP.NS', 'NSE', 'equity', 'Apollo Hospitals',             true, 'Healthcare',    'Nifty 50'),
(gen_random_uuid(), 'BAJAJ-AUTO.NS', 'NSE', 'equity', 'Bajaj Auto',                   true, 'Auto',          'Nifty 50'),
(gen_random_uuid(), 'EICHERMOT.NS',  'NSE', 'equity', 'Eicher Motors',                true, 'Auto',          'Nifty 50'),
(gen_random_uuid(), 'HEROMOTOCO.NS', 'NSE', 'equity', 'Hero MotoCorp',                true, 'Auto',          'Nifty 50'),
(gen_random_uuid(), 'BRITANNIA.NS',  'NSE', 'equity', 'Britannia Industries',         true, 'FMCG',          'Nifty 50'),
(gen_random_uuid(), 'GRASIM.NS',     'NSE', 'equity', 'Grasim Industries',            true, 'Cement',        'Nifty 50'),
(gen_random_uuid(), 'TATACONSUM.NS', 'NSE', 'equity', 'Tata Consumer Products',       true, 'FMCG',          'Nifty 50'),
(gen_random_uuid(), 'SHRIRAMFIN.NS', 'NSE', 'equity', 'Shriram Finance',              true, 'NBFC',          'Nifty 50'),
(gen_random_uuid(), 'BEL.NS',        'NSE', 'equity', 'Bharat Electronics',           true, 'Defence',       'Nifty 50'),
(gen_random_uuid(), 'INDUSINDBK.NS', 'NSE', 'equity', 'IndusInd Bank',                true, 'Banking',       'Nifty 50'),
(gen_random_uuid(), 'BPCL.NS',       'NSE', 'equity', 'Bharat Petroleum',             true, 'Energy',        'Nifty 50'),
(gen_random_uuid(), 'SBILIFE.NS',    'NSE', 'equity', 'SBI Life Insurance',           true, 'Insurance',     'Nifty 50'),
(gen_random_uuid(), 'HDFCLIFE.NS',   'NSE', 'equity', 'HDFC Life Insurance',          true, 'Insurance',     'Nifty 50'),

-- ─── Nifty Next 50 ───────────────────────────────────────────────────────────
(gen_random_uuid(), 'ABB.NS',        'NSE', 'equity', 'ABB India',                    true, 'Capital Goods',    'Nifty Next 50'),
(gen_random_uuid(), 'ABCAPITAL.NS',  'NSE', 'equity', 'Aditya Birla Capital',         true, 'NBFC',             'Nifty Next 50'),
(gen_random_uuid(), 'ADANIGREEN.NS', 'NSE', 'equity', 'Adani Green Energy',           true, 'Power',            'Nifty Next 50'),
(gen_random_uuid(), 'ADANIPOWER.NS', 'NSE', 'equity', 'Adani Power',                  true, 'Power',            'Nifty Next 50'),
(gen_random_uuid(), 'AMBUJACEM.NS',  'NSE', 'equity', 'Ambuja Cements',               true, 'Cement',           'Nifty Next 50'),
(gen_random_uuid(), 'ATGL.NS',       'NSE', 'equity', 'Adani Total Gas',              true, 'Energy',           'Nifty Next 50'),
(gen_random_uuid(), 'AUBANK.NS',     'NSE', 'equity', 'AU Small Finance Bank',        true, 'Banking',          'Nifty Next 50'),
(gen_random_uuid(), 'BANKBARODA.NS', 'NSE', 'equity', 'Bank of Baroda',               true, 'Banking',          'Nifty Next 50'),
(gen_random_uuid(), 'BERGEPAINT.NS', 'NSE', 'equity', 'Berger Paints',                true, 'Paints',           'Nifty Next 50'),
(gen_random_uuid(), 'BIOCON.NS',     'NSE', 'equity', 'Biocon',                       true, 'Pharma',           'Nifty Next 50'),
(gen_random_uuid(), 'BOSCHLTD.NS',   'NSE', 'equity', 'Bosch',                        true, 'Auto Ancillary',   'Nifty Next 50'),
(gen_random_uuid(), 'CANBK.NS',      'NSE', 'equity', 'Canara Bank',                  true, 'Banking',          'Nifty Next 50'),
(gen_random_uuid(), 'CHOLAFIN.NS',   'NSE', 'equity', 'Cholamandalam Investment',     true, 'NBFC',             'Nifty Next 50'),
(gen_random_uuid(), 'COLPAL.NS',     'NSE', 'equity', 'Colgate-Palmolive India',      true, 'FMCG',             'Nifty Next 50'),
(gen_random_uuid(), 'CUMMINSIND.NS', 'NSE', 'equity', 'Cummins India',                true, 'Capital Goods',    'Nifty Next 50'),
(gen_random_uuid(), 'DELHIVERY.NS',  'NSE', 'equity', 'Delhivery',                    true, 'Logistics',        'Nifty Next 50'),
(gen_random_uuid(), 'GODREJCP.NS',   'NSE', 'equity', 'Godrej Consumer Products',     true, 'FMCG',             'Nifty Next 50'),
(gen_random_uuid(), 'GODREJPROP.NS', 'NSE', 'equity', 'Godrej Properties',            true, 'Realty',           'Nifty Next 50'),
(gen_random_uuid(), 'HINDPETRO.NS',  'NSE', 'equity', 'Hindustan Petroleum',          true, 'Energy',           'Nifty Next 50'),
(gen_random_uuid(), 'ICICIGI.NS',    'NSE', 'equity', 'ICICI Lombard GIC',            true, 'Insurance',        'Nifty Next 50'),
(gen_random_uuid(), 'ICICIPRULI.NS', 'NSE', 'equity', 'ICICI Prudential Life',        true, 'Insurance',        'Nifty Next 50'),
(gen_random_uuid(), 'INDUSTOWER.NS', 'NSE', 'equity', 'Indus Towers',                 true, 'Telecom',          'Nifty Next 50'),
(gen_random_uuid(), 'IOC.NS',        'NSE', 'equity', 'Indian Oil Corporation',       true, 'Energy',           'Nifty Next 50'),
(gen_random_uuid(), 'IRCTC.NS',      'NSE', 'equity', 'IRCTC',                        true, 'Tourism',          'Nifty Next 50'),
(gen_random_uuid(), 'JSWENERGY.NS',  'NSE', 'equity', 'JSW Energy',                   true, 'Power',            'Nifty Next 50'),
(gen_random_uuid(), 'JUBLFOOD.NS',   'NSE', 'equity', 'Jubilant Foodworks',           true, 'QSR',              'Nifty Next 50'),
(gen_random_uuid(), 'LICHSGFIN.NS',  'NSE', 'equity', 'LIC Housing Finance',          true, 'NBFC',             'Nifty Next 50'),
(gen_random_uuid(), 'LTIM.NS',       'NSE', 'equity', 'LTIMindtree',                  true, 'IT',               'Nifty Next 50'),
(gen_random_uuid(), 'MFSL.NS',       'NSE', 'equity', 'Max Financial Services',       true, 'Insurance',        'Nifty Next 50'),
(gen_random_uuid(), 'MPHASIS.NS',    'NSE', 'equity', 'Mphasis',                      true, 'IT',               'Nifty Next 50'),
(gen_random_uuid(), 'MRF.NS',        'NSE', 'equity', 'MRF',                          true, 'Auto Ancillary',   'Nifty Next 50'),
(gen_random_uuid(), 'NHPC.NS',       'NSE', 'equity', 'NHPC',                         true, 'Power',            'Nifty Next 50'),
(gen_random_uuid(), 'NMDC.NS',       'NSE', 'equity', 'NMDC',                         true, 'Mining',           'Nifty Next 50'),
(gen_random_uuid(), 'OBEROIRLTY.NS', 'NSE', 'equity', 'Oberoi Realty',                true, 'Realty',           'Nifty Next 50'),
(gen_random_uuid(), 'OFSS.NS',       'NSE', 'equity', 'Oracle Financial Services',    true, 'IT',               'Nifty Next 50'),
(gen_random_uuid(), 'PAGEIND.NS',    'NSE', 'equity', 'Page Industries',              true, 'Textile',          'Nifty Next 50'),
(gen_random_uuid(), 'PATANJALI.NS',  'NSE', 'equity', 'Patanjali Foods',              true, 'FMCG',             'Nifty Next 50'),
(gen_random_uuid(), 'PIIND.NS',      'NSE', 'equity', 'PI Industries',                true, 'Agro Chem',        'Nifty Next 50'),
(gen_random_uuid(), 'PRESTIGE.NS',   'NSE', 'equity', 'Prestige Estates',             true, 'Realty',           'Nifty Next 50'),
(gen_random_uuid(), 'RECLTD.NS',     'NSE', 'equity', 'REC',                          true, 'Power Finance',    'Nifty Next 50'),
(gen_random_uuid(), 'SBICARD.NS',    'NSE', 'equity', 'SBI Cards',                    true, 'NBFC',             'Nifty Next 50'),
(gen_random_uuid(), 'SHREECEM.NS',   'NSE', 'equity', 'Shree Cement',                 true, 'Cement',           'Nifty Next 50'),
(gen_random_uuid(), 'SIEMENS.NS',    'NSE', 'equity', 'Siemens',                      true, 'Capital Goods',    'Nifty Next 50'),
(gen_random_uuid(), 'TATACOMM.NS',   'NSE', 'equity', 'Tata Communications',          true, 'Telecom',          'Nifty Next 50'),
(gen_random_uuid(), 'TORNTPHARM.NS', 'NSE', 'equity', 'Torrent Pharmaceuticals',      true, 'Pharma',           'Nifty Next 50'),
(gen_random_uuid(), 'UNIONBANK.NS',  'NSE', 'equity', 'Union Bank of India',          true, 'Banking',          'Nifty Next 50'),
(gen_random_uuid(), 'UPL.NS',        'NSE', 'equity', 'UPL',                          true, 'Agro Chem',        'Nifty Next 50'),
(gen_random_uuid(), 'VBL.NS',        'NSE', 'equity', 'Varun Beverages',              true, 'Beverages',        'Nifty Next 50'),
(gen_random_uuid(), 'VEDL.NS',       'NSE', 'equity', 'Vedanta',                      true, 'Metals',           'Nifty Next 50'),
(gen_random_uuid(), 'VOLTAS.NS',     'NSE', 'equity', 'Voltas',                       true, 'Consumer Durables','Nifty Next 50'),
(gen_random_uuid(), 'ZYDUSLIFE.NS',  'NSE', 'equity', 'Zydus Lifesciences',           true, 'Pharma',           'Nifty Next 50'),

-- ─── Nifty Midcap 150 ────────────────────────────────────────────────────────
(gen_random_uuid(), 'AARTIIND.NS',   'NSE', 'equity', 'Aarti Industries',             true, 'Chemicals',        'Nifty Midcap 150'),
(gen_random_uuid(), 'AFFLE.NS',      'NSE', 'equity', 'Affle India',                  true, 'Technology',       'Nifty Midcap 150'),
(gen_random_uuid(), 'AJANTPHARM.NS', 'NSE', 'equity', 'Ajanta Pharma',                true, 'Pharma',           'Nifty Midcap 150'),
(gen_random_uuid(), 'ALKEM.NS',      'NSE', 'equity', 'Alkem Laboratories',           true, 'Pharma',           'Nifty Midcap 150'),
(gen_random_uuid(), 'AMBER.NS',      'NSE', 'equity', 'Amber Enterprises',            true, 'Consumer Durables','Nifty Midcap 150'),
(gen_random_uuid(), 'ANGELONE.NS',   'NSE', 'equity', 'Angel One',                    true, 'Broking',          'Nifty Midcap 150'),
(gen_random_uuid(), 'APARINDS.NS',   'NSE', 'equity', 'Apar Industries',              true, 'Capital Goods',    'Nifty Midcap 150'),
(gen_random_uuid(), 'APLLTD.NS',     'NSE', 'equity', 'APL Apollo Tubes',             true, 'Pharma',           'Nifty Midcap 150'),
(gen_random_uuid(), 'ASTRAL.NS',     'NSE', 'equity', 'Astral',                       true, 'Pipes',            'Nifty Midcap 150'),
(gen_random_uuid(), 'ATUL.NS',       'NSE', 'equity', 'Atul',                         true, 'Chemicals',        'Nifty Midcap 150'),
(gen_random_uuid(), 'AUROBINDO.NS',  'NSE', 'equity', 'Aurobindo Pharma',             true, 'Pharma',           'Nifty Midcap 150'),
(gen_random_uuid(), 'AVANTIFEED.NS', 'NSE', 'equity', 'Avanti Feeds',                 true, 'Aquaculture',      'Nifty Midcap 150'),
(gen_random_uuid(), 'BALRAMCHIN.NS', 'NSE', 'equity', 'Balrampur Chini Mills',        true, 'Sugar',            'Nifty Midcap 150'),
(gen_random_uuid(), 'BSOFT.NS',      'NSE', 'equity', 'Birlasoft',                    true, 'IT',               'Nifty Midcap 150'),
(gen_random_uuid(), 'CAMS.NS',       'NSE', 'equity', 'Computer Age Mgmt Services',   true, 'Financial Services','Nifty Midcap 150'),
(gen_random_uuid(), 'CANFINHOME.NS', 'NSE', 'equity', 'Can Fin Homes',                true, 'NBFC',             'Nifty Midcap 150'),
(gen_random_uuid(), 'CDSL.NS',       'NSE', 'equity', 'Central Depository Services',  true, 'Financial Services','Nifty Midcap 150'),
(gen_random_uuid(), 'CENTURYTEX.NS', 'NSE', 'equity', 'Century Textiles',             true, 'Textile',          'Nifty Midcap 150'),
(gen_random_uuid(), 'CGPOWER.NS',    'NSE', 'equity', 'CG Power & Industrial',        true, 'Capital Goods',    'Nifty Midcap 150'),
(gen_random_uuid(), 'COFORGE.NS',    'NSE', 'equity', 'Coforge',                      true, 'IT',               'Nifty Midcap 150'),
(gen_random_uuid(), 'CROMPTON.NS',   'NSE', 'equity', 'Crompton Greaves Consumer',    true, 'Consumer Durables','Nifty Midcap 150'),
(gen_random_uuid(), 'DALBHARAT.NS',  'NSE', 'equity', 'Dalmia Bharat',                true, 'Cement',           'Nifty Midcap 150'),
(gen_random_uuid(), 'DEEPAKNTR.NS',  'NSE', 'equity', 'Deepak Nitrite',               true, 'Chemicals',        'Nifty Midcap 150'),
(gen_random_uuid(), 'DIXON.NS',      'NSE', 'equity', 'Dixon Technologies',           true, 'Electronics',      'Nifty Midcap 150'),
(gen_random_uuid(), 'ELGIEQUIP.NS',  'NSE', 'equity', 'Elgi Equipments',              true, 'Capital Goods',    'Nifty Midcap 150'),
(gen_random_uuid(), 'EMCURE.NS',     'NSE', 'equity', 'Emcure Pharmaceuticals',       true, 'Pharma',           'Nifty Midcap 150'),
(gen_random_uuid(), 'ENDURANCE.NS',  'NSE', 'equity', 'Endurance Technologies',       true, 'Auto Ancillary',   'Nifty Midcap 150'),
(gen_random_uuid(), 'ESCORTS.NS',    'NSE', 'equity', 'Escorts Kubota',               true, 'Auto',             'Nifty Midcap 150'),
(gen_random_uuid(), 'EXIDEIND.NS',   'NSE', 'equity', 'Exide Industries',             true, 'Auto Ancillary',   'Nifty Midcap 150'),
(gen_random_uuid(), 'FINEORG.NS',    'NSE', 'equity', 'Fine Organic Industries',      true, 'Chemicals',        'Nifty Midcap 150'),
(gen_random_uuid(), 'GLAND.NS',      'NSE', 'equity', 'Gland Pharma',                 true, 'Pharma',           'Nifty Midcap 150'),
(gen_random_uuid(), 'GODREJIND.NS',  'NSE', 'equity', 'Godrej Industries',            true, 'Conglomerate',     'Nifty Midcap 150'),
(gen_random_uuid(), 'GUJGASLTD.NS',  'NSE', 'equity', 'Gujarat Gas',                  true, 'Gas',              'Nifty Midcap 150'),
(gen_random_uuid(), 'IDFCFIRSTB.NS', 'NSE', 'equity', 'IDFC First Bank',              true, 'Banking',          'Nifty Midcap 150'),
(gen_random_uuid(), 'IEX.NS',        'NSE', 'equity', 'Indian Energy Exchange',       true, 'Power',            'Nifty Midcap 150'),
(gen_random_uuid(), 'INTELLECT.NS',  'NSE', 'equity', 'Intellect Design Arena',       true, 'IT',               'Nifty Midcap 150'),
(gen_random_uuid(), 'IRFC.NS',       'NSE', 'equity', 'Indian Railway Finance Corp',  true, 'Power Finance',    'Nifty Midcap 150'),
(gen_random_uuid(), 'JBCHEPHARM.NS', 'NSE', 'equity', 'JB Chemicals & Pharma',        true, 'Pharma',           'Nifty Midcap 150'),
(gen_random_uuid(), 'JKCEMENT.NS',   'NSE', 'equity', 'JK Cement',                    true, 'Cement',           'Nifty Midcap 150'),
(gen_random_uuid(), 'JKTYRE.NS',     'NSE', 'equity', 'JK Tyre & Industries',         true, 'Auto Ancillary',   'Nifty Midcap 150'),
(gen_random_uuid(), 'KANSAINER.NS',  'NSE', 'equity', 'Kansai Nerolac Paints',        true, 'Paints',           'Nifty Midcap 150'),
(gen_random_uuid(), 'KARURVYSYA.NS', 'NSE', 'equity', 'Karur Vysya Bank',             true, 'Banking',          'Nifty Midcap 150'),
(gen_random_uuid(), 'KAYNES.NS',     'NSE', 'equity', 'Kaynes Technology',            true, 'Electronics',      'Nifty Midcap 150'),
(gen_random_uuid(), 'KEI.NS',        'NSE', 'equity', 'KEI Industries',               true, 'Cables',           'Nifty Midcap 150'),
(gen_random_uuid(), 'KFINTECH.NS',   'NSE', 'equity', 'KFin Technologies',            true, 'Financial Services','Nifty Midcap 150'),
(gen_random_uuid(), 'KIMS.NS',       'NSE', 'equity', 'Krishna Institute of Medical', true, 'Healthcare',       'Nifty Midcap 150'),
(gen_random_uuid(), 'KPRMILL.NS',    'NSE', 'equity', 'KPR Mill',                     true, 'Textile',          'Nifty Midcap 150'),
(gen_random_uuid(), 'LATENTVIEW.NS', 'NSE', 'equity', 'LatentView Analytics',         true, 'Analytics',        'Nifty Midcap 150'),
(gen_random_uuid(), 'LICI.NS',       'NSE', 'equity', 'LIC of India',                 true, 'Insurance',        'Nifty Midcap 150'),
(gen_random_uuid(), 'LINDEINDIA.NS', 'NSE', 'equity', 'Linde India',                  true, 'Industrial Gas',   'Nifty Midcap 150'),
(gen_random_uuid(), 'LTTS.NS',       'NSE', 'equity', 'L&T Technology Services',      true, 'IT',               'Nifty Midcap 150'),
(gen_random_uuid(), 'MAXHEALTH.NS',  'NSE', 'equity', 'Max Healthcare',               true, 'Healthcare',       'Nifty Midcap 150'),
(gen_random_uuid(), 'MCX.NS',        'NSE', 'equity', 'Multi Commodity Exchange',      true, 'Exchange',         'Nifty Midcap 150'),
(gen_random_uuid(), 'METROPOLIS.NS', 'NSE', 'equity', 'Metropolis Healthcare',        true, 'Diagnostics',      'Nifty Midcap 150'),
(gen_random_uuid(), 'NATCOPHARM.NS', 'NSE', 'equity', 'Natco Pharma',                 true, 'Pharma',           'Nifty Midcap 150'),
(gen_random_uuid(), 'NAVINFLUOR.NS', 'NSE', 'equity', 'Navin Fluorine',               true, 'Chemicals',        'Nifty Midcap 150'),
(gen_random_uuid(), 'INFOEDGE.NS',   'NSE', 'equity', 'Info Edge India',              true, 'Internet',         'Nifty Midcap 150'),
(gen_random_uuid(), 'NUVAMA.NS',     'NSE', 'equity', 'Nuvama Wealth Management',     true, 'Financial Services','Nifty Midcap 150'),
(gen_random_uuid(), 'PCBL.NS',       'NSE', 'equity', 'PCBL',                         true, 'Carbon Black',     'Nifty Midcap 150'),
(gen_random_uuid(), 'PERSISTENT.NS', 'NSE', 'equity', 'Persistent Systems',           true, 'IT',               'Nifty Midcap 150'),
(gen_random_uuid(), 'PHOENIXLTD.NS', 'NSE', 'equity', 'The Phoenix Mills',            true, 'Retail',           'Nifty Midcap 150'),
(gen_random_uuid(), 'POLYMED.NS',    'NSE', 'equity', 'Poly Medicure',                true, 'Healthcare',       'Nifty Midcap 150'),
(gen_random_uuid(), 'POONAWALLA.NS', 'NSE', 'equity', 'Poonawalla Fincorp',           true, 'NBFC',             'Nifty Midcap 150'),
(gen_random_uuid(), 'RADICO.NS',     'NSE', 'equity', 'Radico Khaitan',               true, 'Beverages',        'Nifty Midcap 150'),
(gen_random_uuid(), 'RAMCOCEM.NS',   'NSE', 'equity', 'Ramco Cements',                true, 'Cement',           'Nifty Midcap 150'),
(gen_random_uuid(), 'RBLBANK.NS',    'NSE', 'equity', 'RBL Bank',                     true, 'Banking',          'Nifty Midcap 150'),
(gen_random_uuid(), 'RELAXO.NS',     'NSE', 'equity', 'Relaxo Footwears',             true, 'Footwear',         'Nifty Midcap 150'),
(gen_random_uuid(), 'ROUTE.NS',      'NSE', 'equity', 'Route Mobile',                 true, 'IT',               'Nifty Midcap 150'),
(gen_random_uuid(), 'SAFARI.NS',     'NSE', 'equity', 'Safari Industries',            true, 'Luggage',          'Nifty Midcap 150'),
(gen_random_uuid(), 'SCHAEFFLER.NS', 'NSE', 'equity', 'Schaeffler India',             true, 'Auto Ancillary',   'Nifty Midcap 150'),
(gen_random_uuid(), 'SKFINDIA.NS',   'NSE', 'equity', 'SKF India',                    true, 'Auto Ancillary',   'Nifty Midcap 150'),
(gen_random_uuid(), 'SOBHA.NS',      'NSE', 'equity', 'Sobha',                        true, 'Realty',           'Nifty Midcap 150'),
(gen_random_uuid(), 'SONACOMS.NS',   'NSE', 'equity', 'Sona BLW Precision',          true, 'Auto Ancillary',   'Nifty Midcap 150'),
(gen_random_uuid(), 'STARHEALTH.NS', 'NSE', 'equity', 'Star Health Insurance',        true, 'Insurance',        'Nifty Midcap 150'),
(gen_random_uuid(), 'SUNDARMFIN.NS', 'NSE', 'equity', 'Sundaram Finance',             true, 'NBFC',             'Nifty Midcap 150'),
(gen_random_uuid(), 'SUNTV.NS',      'NSE', 'equity', 'Sun TV Network',               true, 'Media',            'Nifty Midcap 150'),
(gen_random_uuid(), 'SUZLON.NS',     'NSE', 'equity', 'Suzlon Energy',                true, 'Power',            'Nifty Midcap 150'),
(gen_random_uuid(), 'SWSOLAR.NS',    'NSE', 'equity', 'Sterling and Wilson Solar',    true, 'Power',            'Nifty Midcap 150'),
(gen_random_uuid(), 'TANLA.NS',      'NSE', 'equity', 'Tanla Platforms',              true, 'Technology',       'Nifty Midcap 150'),
(gen_random_uuid(), 'TATACHEM.NS',   'NSE', 'equity', 'Tata Chemicals',               true, 'Chemicals',        'Nifty Midcap 150'),
(gen_random_uuid(), 'TATAELXSI.NS',  'NSE', 'equity', 'Tata Elxsi',                   true, 'IT',               'Nifty Midcap 150'),
(gen_random_uuid(), 'TIINDIA.NS',    'NSE', 'equity', 'Tube Investments of India',    true, 'Auto Ancillary',   'Nifty Midcap 150'),
(gen_random_uuid(), 'TIMKEN.NS',     'NSE', 'equity', 'Timken India',                 true, 'Auto Ancillary',   'Nifty Midcap 150'),
(gen_random_uuid(), 'TORNTPOWER.NS', 'NSE', 'equity', 'Torrent Power',                true, 'Power',            'Nifty Midcap 150'),
(gen_random_uuid(), 'TRIDENT.NS',    'NSE', 'equity', 'Trident',                      true, 'Textile',          'Nifty Midcap 150'),
(gen_random_uuid(), 'TRENT.NS',      'NSE', 'equity', 'Trent',                        true, 'Retail',           'Nifty Midcap 150'),
(gen_random_uuid(), 'UJJIVAN.NS',    'NSE', 'equity', 'Ujjivan Financial Services',   true, 'Banking',          'Nifty Midcap 150'),
(gen_random_uuid(), 'VINATIORGA.NS', 'NSE', 'equity', 'Vinati Organics',              true, 'Chemicals',        'Nifty Midcap 150'),
(gen_random_uuid(), 'VSTIND.NS',     'NSE', 'equity', 'VST Industries',               true, 'FMCG',             'Nifty Midcap 150'),
(gen_random_uuid(), 'WELSPUNLIV.NS', 'NSE', 'equity', 'Welspun Living',               true, 'Textile',          'Nifty Midcap 150'),
(gen_random_uuid(), 'WHIRLPOOL.NS',  'NSE', 'equity', 'Whirlpool of India',           true, 'Consumer Durables','Nifty Midcap 150'),
(gen_random_uuid(), 'ZEEL.NS',       'NSE', 'equity', 'Zee Entertainment',            true, 'Media',            'Nifty Midcap 150'),

-- ─── Nifty Smallcap 250 (top ~130 well-known) ────────────────────────────────
(gen_random_uuid(), 'AARTIDRUGS.NS', 'NSE', 'equity', 'Aarti Drugs',                  true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'AAVAS.NS',      'NSE', 'equity', 'Aavas Financiers',             true, 'NBFC',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'ACE.NS',        'NSE', 'equity', 'Action Construction Equipment',true, 'Capital Goods',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'AETHER.NS',     'NSE', 'equity', 'Aether Industries',            true, 'Chemicals',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'AIAENG.NS',     'NSE', 'equity', 'AIA Engineering',              true, 'Capital Goods',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'ALKYLAMINE.NS', 'NSE', 'equity', 'Alkyl Amines Chemicals',       true, 'Chemicals',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'ALLCARGO.NS',   'NSE', 'equity', 'Allcargo Logistics',           true, 'Logistics',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'AMARAJABAT.NS', 'NSE', 'equity', 'Amara Raja Energy & Mobility', true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'ANURAS.NS',     'NSE', 'equity', 'Anuras',                       true, 'Healthcare',       'Nifty Smallcap 250'),
(gen_random_uuid(), 'APTUS.NS',      'NSE', 'equity', 'Aptus Value Housing Finance',  true, 'NBFC',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'ASHOKA.NS',     'NSE', 'equity', 'Ashoka Buildcon',              true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'ASHOKVLKS.NS',  'NSE', 'equity', 'Ashok Leyland',                true, 'Auto',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'ASTERDM.NS',    'NSE', 'equity', 'Aster DM Healthcare',          true, 'Healthcare',       'Nifty Smallcap 250'),
(gen_random_uuid(), 'BALKRISIND.NS', 'NSE', 'equity', 'Balkrishna Industries',        true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'BANKINDIA.NS',  'NSE', 'equity', 'Bank of India',                true, 'Banking',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'BEML.NS',       'NSE', 'equity', 'BEML',                         true, 'Defence',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'BLUESTARCO.NS', 'NSE', 'equity', 'Blue Star',                    true, 'Consumer Durables','Nifty Smallcap 250'),
(gen_random_uuid(), 'BRIGADE.NS',    'NSE', 'equity', 'Brigade Enterprises',          true, 'Realty',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'CEATLTD.NS',    'NSE', 'equity', 'CEAT',                         true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'CENTRALBK.NS',  'NSE', 'equity', 'Central Bank of India',        true, 'Banking',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'COCHINSHIP.NS', 'NSE', 'equity', 'Cochin Shipyard',              true, 'Defence',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'CRAFTSMAN.NS',  'NSE', 'equity', 'Craftsman Automation',         true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'DATAPATTNS.NS', 'NSE', 'equity', 'Data Patterns India',          true, 'Defence',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'DCMSHRIRAM.NS', 'NSE', 'equity', 'DCM Shriram',                  true, 'Chemicals',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'DEEPAKFERT.NS', 'NSE', 'equity', 'Deepak Fertilisers',           true, 'Fertilizer',       'Nifty Smallcap 250'),
(gen_random_uuid(), 'DHANUKA.NS',    'NSE', 'equity', 'Dhanuka Agritech',             true, 'Agro Chem',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'ECLERX.NS',     'NSE', 'equity', 'eClerx Services',              true, 'IT',               'Nifty Smallcap 250'),
(gen_random_uuid(), 'ELECON.NS',     'NSE', 'equity', 'Elecon Engineering',           true, 'Capital Goods',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'ENGINERSIN.NS', 'NSE', 'equity', 'Engineers India',              true, 'Defence',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'EPL.NS',        'NSE', 'equity', 'EPL',                          true, 'Packaging',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'EQUITASBNK.NS', 'NSE', 'equity', 'Equitas Small Finance Bank',   true, 'Banking',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'ESABINDIA.NS',  'NSE', 'equity', 'Esab India',                   true, 'Capital Goods',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'FEDERALBNK.NS', 'NSE', 'equity', 'Federal Bank',                 true, 'Banking',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'FLUOROCHEM.NS', 'NSE', 'equity', 'Gujarat Fluorochemicals',      true, 'Chemicals',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'GHCL.NS',       'NSE', 'equity', 'GHCL',                         true, 'Chemicals',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'GODREJAGRO.NS', 'NSE', 'equity', 'Godrej Agrovet',               true, 'Agro',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'GPIL.NS',       'NSE', 'equity', 'Godawari Power & Ispat',       true, 'Steel',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'GRANULES.NS',   'NSE', 'equity', 'Granules India',               true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'GRINDWELL.NS',  'NSE', 'equity', 'Grindwell Norton',             true, 'Capital Goods',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'GRSE.NS',       'NSE', 'equity', 'Garden Reach Shipbuilders',    true, 'Defence',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'GSPL.NS',       'NSE', 'equity', 'Gujarat State Petronet',       true, 'Gas',              'Nifty Smallcap 250'),
(gen_random_uuid(), 'HAPPSTMNDS.NS', 'NSE', 'equity', 'Happiest Minds Technologies',  true, 'IT',               'Nifty Smallcap 250'),
(gen_random_uuid(), 'HBLPOWER.NS',   'NSE', 'equity', 'HBL Power Systems',            true, 'Capital Goods',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'HFCL.NS',       'NSE', 'equity', 'HFCL',                         true, 'Telecom',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'HIKAL.NS',      'NSE', 'equity', 'Hikal',                        true, 'Chemicals',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'HONASA.NS',     'NSE', 'equity', 'Honasa Consumer',              true, 'FMCG',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'HUDCO.NS',      'NSE', 'equity', 'Housing & Urban Dev Corp',     true, 'Finance',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'IBREALEST.NS',  'NSE', 'equity', 'Indiabulls Real Estate',       true, 'Realty',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'INDIAMART.NS',  'NSE', 'equity', 'IndiaMart InterMESH',          true, 'Internet',         'Nifty Smallcap 250'),
(gen_random_uuid(), 'INDIACEM.NS',   'NSE', 'equity', 'India Cements',                true, 'Cement',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'INDIGOPNTS.NS', 'NSE', 'equity', 'Indigo Paints',                true, 'Paints',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'INOXWIND.NS',   'NSE', 'equity', 'Inox Wind',                    true, 'Power',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'IOB.NS',        'NSE', 'equity', 'Indian Overseas Bank',         true, 'Banking',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'IPCA.NS',       'NSE', 'equity', 'IPCA Laboratories',            true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'JAMNAAUTO.NS',  'NSE', 'equity', 'Jamna Auto Industries',        true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'JINDALSTEL.NS', 'NSE', 'equity', 'Jindal Steel & Power',         true, 'Steel',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'JINDALSAW.NS',  'NSE', 'equity', 'Jindal Saw',                   true, 'Steel',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'JKPAPER.NS',    'NSE', 'equity', 'JK Paper',                     true, 'Paper',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'JMFINANCIL.NS', 'NSE', 'equity', 'JM Financial',                 true, 'Finance',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'KALPATPOWR.NS', 'NSE', 'equity', 'Kalpataru Projects Intl',      true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'KNRCON.NS',     'NSE', 'equity', 'KNR Constructions',            true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'KOLTEPATIL.NS', 'NSE', 'equity', 'Kolte-Patil Developers',       true, 'Realty',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'KRBL.NS',       'NSE', 'equity', 'KRBL',                         true, 'FMCG',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'LALPATHLAB.NS', 'NSE', 'equity', 'Dr Lal PathLabs',              true, 'Diagnostics',      'Nifty Smallcap 250'),
(gen_random_uuid(), 'LAURUSLABS.NS', 'NSE', 'equity', 'Laurus Labs',                  true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'LEMONTREE.NS',  'NSE', 'equity', 'Lemon Tree Hotels',            true, 'Hospitality',      'Nifty Smallcap 250'),
(gen_random_uuid(), 'LUMAXTECH.NS',  'NSE', 'equity', 'Lumax Auto Technologies',      true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'MANAPPURAM.NS', 'NSE', 'equity', 'Manappuram Finance',           true, 'NBFC',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'MARICO.NS',     'NSE', 'equity', 'Marico',                       true, 'FMCG',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'MARKSANS.NS',   'NSE', 'equity', 'Marksans Pharma',              true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'MEDANTA.NS',    'NSE', 'equity', 'Global Health (Medanta)',       true, 'Healthcare',       'Nifty Smallcap 250'),
(gen_random_uuid(), 'MIDHANI.NS',    'NSE', 'equity', 'MIDHANI',                      true, 'Defence',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'MINDACORP.NS',  'NSE', 'equity', 'Minda Corporation',            true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'MOLDTKPAC.NS',  'NSE', 'equity', 'Mold-Tek Packaging',           true, 'Packaging',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'MOTILALOFS.NS', 'NSE', 'equity', 'Motilal Oswal Financial',      true, 'Broking',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'MTAR.NS',       'NSE', 'equity', 'MTAR Technologies',            true, 'Defence',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'MUTHOOTFIN.NS', 'NSE', 'equity', 'Muthoot Finance',              true, 'NBFC',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'NBCC.NS',       'NSE', 'equity', 'NBCC India',                   true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'NOCIL.NS',      'NSE', 'equity', 'NOCIL',                        true, 'Chemicals',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'NUVOCO.NS',     'NSE', 'equity', 'Nuvoco Vistas Corporation',    true, 'Cement',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'OLECTRA.NS',    'NSE', 'equity', 'Olectra Greentech',            true, 'Auto',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'ORCHPHARMA.NS', 'NSE', 'equity', 'Orchid Pharma',                true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'PARADEEP.NS',   'NSE', 'equity', 'Paradeep Phosphates',          true, 'Fertilizer',       'Nifty Smallcap 250'),
(gen_random_uuid(), 'PATELENG.NS',   'NSE', 'equity', 'Patel Engineering',            true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'PFIZER.NS',     'NSE', 'equity', 'Pfizer',                       true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'PNCINFRA.NS',   'NSE', 'equity', 'PNC Infratech',                true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'PRAJ.NS',       'NSE', 'equity', 'Praj Industries',              true, 'Capital Goods',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'PTC.NS',        'NSE', 'equity', 'PTC India',                    true, 'Power',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'PVR.NS',        'NSE', 'equity', 'PVR INOX',                     true, 'Entertainment',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'QUICKHEAL.NS',  'NSE', 'equity', 'Quick Heal Technologies',      true, 'IT',               'Nifty Smallcap 250'),
(gen_random_uuid(), 'QUESS.NS',      'NSE', 'equity', 'Quess Corp',                   true, 'Services',         'Nifty Smallcap 250'),
(gen_random_uuid(), 'RAJRATAN.NS',   'NSE', 'equity', 'Rajratan Global Wire',         true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'RALLIS.NS',     'NSE', 'equity', 'Rallis India',                 true, 'Agro Chem',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'RATNAMANI.NS',  'NSE', 'equity', 'Ratnamani Metals & Tubes',     true, 'Steel',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'RAYMOND.NS',    'NSE', 'equity', 'Raymond',                      true, 'Textile',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'RCF.NS',        'NSE', 'equity', 'Rashtriya Chemicals & Fert',   true, 'Fertilizer',       'Nifty Smallcap 250'),
(gen_random_uuid(), 'REDINGTON.NS',  'NSE', 'equity', 'Redington',                    true, 'IT Distribution',  'Nifty Smallcap 250'),
(gen_random_uuid(), 'RITES.NS',      'NSE', 'equity', 'RITES',                        true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'SANOFI.NS',     'NSE', 'equity', 'Sanofi India',                 true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'SAREGAMA.NS',   'NSE', 'equity', 'Saregama India',               true, 'Media',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'SEQUENT.NS',    'NSE', 'equity', 'Sequent Scientific',           true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'SHANKARA.NS',   'NSE', 'equity', 'Shankara Building Products',   true, 'Steel',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'SHOPERSTOP.NS', 'NSE', 'equity', 'Shoppers Stop',                true, 'Retail',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'SKIPPER.NS',    'NSE', 'equity', 'Skipper',                      true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'SPANDANA.NS',   'NSE', 'equity', 'Spandana Sphoorty Fin',        true, 'NBFC',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'SRTRANSFIN.NS', 'NSE', 'equity', 'Shriram Transport Finance',    true, 'NBFC',             'Nifty Smallcap 250'),
(gen_random_uuid(), 'STARCEMENT.NS', 'NSE', 'equity', 'Star Cement',                  true, 'Cement',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'STLTECH.NS',    'NSE', 'equity', 'Sterlite Technologies',        true, 'Telecom',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'SUDARSCHEM.NS', 'NSE', 'equity', 'Sudarshan Chemical',           true, 'Chemicals',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'SUMICHEM.NS',   'NSE', 'equity', 'Sumitomo Chemical India',      true, 'Agro Chem',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'SUPRIYA.NS',    'NSE', 'equity', 'Supriya Lifescience',          true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'SYNGENE.NS',    'NSE', 'equity', 'Syngene International',        true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'TATAINVEST.NS', 'NSE', 'equity', 'Tata Investment Corp',         true, 'Finance',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'TEAMLEASE.NS',  'NSE', 'equity', 'TeamLease Services',           true, 'Services',         'Nifty Smallcap 250'),
(gen_random_uuid(), 'TEJASNET.NS',   'NSE', 'equity', 'Tejas Networks',               true, 'Telecom',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'THYROCARE.NS',  'NSE', 'equity', 'Thyrocare Technologies',       true, 'Diagnostics',      'Nifty Smallcap 250'),
(gen_random_uuid(), 'TRIVENI.NS',    'NSE', 'equity', 'Triveni Engineering',          true, 'Sugar',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'TTKHLTCARE.NS', 'NSE', 'equity', 'TTK Healthcare',               true, 'Healthcare',       'Nifty Smallcap 250'),
(gen_random_uuid(), 'TTKPRESTIG.NS', 'NSE', 'equity', 'TTK Prestige',                 true, 'Consumer Durables','Nifty Smallcap 250'),
(gen_random_uuid(), 'UCOBANK.NS',    'NSE', 'equity', 'UCO Bank',                     true, 'Banking',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'UJJIVANSFB.NS', 'NSE', 'equity', 'Ujjivan Small Finance Bank',   true, 'Banking',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'UNOMINDA.NS',   'NSE', 'equity', 'UNO Minda',                    true, 'Auto Ancillary',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'VAIBHAVGBL.NS', 'NSE', 'equity', 'Vaibhav Global',               true, 'Jewellery',        'Nifty Smallcap 250'),
(gen_random_uuid(), 'VGUARD.NS',     'NSE', 'equity', 'V-Guard Industries',           true, 'Consumer Durables','Nifty Smallcap 250'),
(gen_random_uuid(), 'VIMTALABS.NS',  'NSE', 'equity', 'Vimta Labs',                   true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'VMART.NS',      'NSE', 'equity', 'V-Mart Retail',                true, 'Retail',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'VOLTAMP.NS',    'NSE', 'equity', 'Voltamp Transformers',         true, 'Capital Goods',    'Nifty Smallcap 250'),
(gen_random_uuid(), 'WABAG.NS',      'NSE', 'equity', 'VA Tech Wabag',                true, 'Infrastructure',   'Nifty Smallcap 250'),
(gen_random_uuid(), 'WELCORP.NS',    'NSE', 'equity', 'Welspun Corp',                 true, 'Steel',            'Nifty Smallcap 250'),
(gen_random_uuid(), 'WELSPUNIND.NS', 'NSE', 'equity', 'Welspun India',                true, 'Textile',          'Nifty Smallcap 250'),
(gen_random_uuid(), 'WINDLAS.NS',    'NSE', 'equity', 'Windlas Biotech',              true, 'Pharma',           'Nifty Smallcap 250'),
(gen_random_uuid(), 'YATHARTH.NS',   'NSE', 'equity', 'Yatharth Hospital',            true, 'Healthcare',       'Nifty Smallcap 250'),
(gen_random_uuid(), 'ZENSARTECH.NS', 'NSE', 'equity', 'Zensar Technologies',          true, 'IT',               'Nifty Smallcap 250')

ON CONFLICT (symbol, exchange) DO UPDATE SET
    sector     = EXCLUDED.sector,
    index_name = EXCLUDED.index_name,
    name       = COALESCE(EXCLUDED.name, universe.name);
